import type { Activity, WeekendTheme } from "./types"

// Generic activities that work anywhere
export const PREDEFINED_ACTIVITIES: Activity[] = [
  // Outdoor Activities
  {
    id: "hiking",
    name: "Hiking",
    category: "outdoor",
    duration: 180,
    icon: "🥾",
    description: "Explore nature trails and enjoy fresh air",
    mood: "adventurous",
  },
  {
    id: "cycling",
    name: "Cycling",
    category: "outdoor",
    duration: 120,
    icon: "🚴",
    description: "Bike ride through scenic routes",
    mood: "energetic",
  },
  {
    id: "picnic",
    name: "Picnic",
    category: "outdoor",
    duration: 150,
    icon: "🧺",
    description: "Outdoor meal in a beautiful setting",
    mood: "relaxed",
  },
  {
    id: "gardening",
    name: "Gardening",
    category: "outdoor",
    duration: 90,
    icon: "🌱",
    description: "Tend to plants and flowers",
    mood: "relaxed",
  },

  // Indoor Activities
  {
    id: "reading",
    name: "Reading",
    category: "indoor",
    duration: 120,
    icon: "📚",
    description: "Dive into a good book",
    mood: "relaxed",
  },
  {
    id: "cooking",
    name: "Cooking",
    category: "indoor",
    duration: 90,
    icon: "👨‍🍳",
    description: "Prepare a delicious meal",
    mood: "happy",
  },
  {
    id: "art-crafts",
    name: "Arts & Crafts",
    category: "indoor",
    duration: 120,
    icon: "🎨",
    description: "Creative projects and DIY",
    mood: "happy",
  },
  {
    id: "gaming",
    name: "Gaming",
    category: "indoor",
    duration: 180,
    icon: "🎮",
    description: "Video games or board games",
    mood: "energetic",
  },

  // Social Activities
  {
    id: "friends-hangout",
    name: "Friends Hangout",
    category: "social",
    duration: 240,
    icon: "👥",
    description: "Spend quality time with friends",
    mood: "happy",
  },
  {
    id: "family-time",
    name: "Family Time",
    category: "social",
    duration: 180,
    icon: "👨‍👩‍👧‍👦",
    description: "Quality time with family",
    mood: "happy",
  },
  {
    id: "party",
    name: "Party",
    category: "social",
    duration: 300,
    icon: "🎉",
    description: "Celebrate with friends",
    mood: "energetic",
  },

  // Wellness Activities
  {
    id: "yoga",
    name: "Yoga",
    category: "wellness",
    duration: 60,
    icon: "🧘",
    description: "Mindful movement and stretching",
    mood: "relaxed",
  },
  {
    id: "meditation",
    name: "Meditation",
    category: "wellness",
    duration: 30,
    icon: "🕯️",
    description: "Mindfulness and relaxation",
    mood: "relaxed",
  },
  {
    id: "spa-day",
    name: "Spa Day",
    category: "wellness",
    duration: 180,
    icon: "🛁",
    description: "Self-care and pampering",
    mood: "relaxed",
  },
  {
    id: "workout",
    name: "Workout",
    category: "wellness",
    duration: 60,
    icon: "💪",
    description: "Exercise and fitness",
    mood: "energetic",
  },

  // Food Activities
  {
    id: "brunch",
    name: "Brunch",
    category: "food",
    duration: 120,
    icon: "🥞",
    description: "Late morning meal with friends",
    mood: "happy",
  },
  {
    id: "restaurant",
    name: "Restaurant Visit",
    category: "food",
    duration: 90,
    icon: "🍽️",
    description: "Dine out at a nice restaurant",
    mood: "happy",
  },
  {
    id: "food-market",
    name: "Food Market",
    category: "food",
    duration: 120,
    icon: "🛒",
    description: "Explore local farmers market",
    mood: "adventurous",
  },

  // Entertainment Activities
  {
    id: "movie-night",
    name: "Movie Night",
    category: "entertainment",
    duration: 150,
    icon: "🎬",
    description: "Watch movies at home or cinema",
    mood: "relaxed",
  },
  {
    id: "concert",
    name: "Concert",
    category: "entertainment",
    duration: 180,
    icon: "🎵",
    description: "Live music performance",
    mood: "energetic",
  },
  {
    id: "museum",
    name: "Museum Visit",
    category: "entertainment",
    duration: 150,
    icon: "🏛️",
    description: "Explore art and culture",
    mood: "adventurous",
  },
  {
    id: "shopping",
    name: "Shopping",
    category: "entertainment",
    duration: 180,
    icon: "🛍️",
    description: "Browse stores and find treasures",
    mood: "happy",
  },
]

// Pune-specific locations for AI suggestions
export const PUNE_LOCATIONS: Activity[] = [
  {
    id: "shaniwar-wada",
    name: "Shaniwar Wada",
    category: "entertainment",
    duration: 90,
    icon: "🏰",
    description: "Historic fortification and palace ruins in Pune city center",
    mood: "adventurous",
    mapImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "aga-khan-palace",
    name: "Aga Khan Palace",
    category: "entertainment",
    duration: 120,
    icon: "🏛️",
    description: "Beautiful Italianate arches and lush gardens with Gandhi history",
    mood: "relaxed",
    mapImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "sinhagad-fort",
    name: "Sinhagad Fort",
    category: "outdoor",
    duration: 240,
    icon: "⛰️",
    description: "Ancient hill fortress with trekking trails and panoramic views",
    mood: "adventurous",
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "fc-road",
    name: "FC Road Food Walk",
    category: "food",
    duration: 150,
    icon: "🍔",
    description: "Street food paradise on Fergusson College Road",
    mood: "happy",
    mapImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "saras-baug",
    name: "Saras Baug",
    category: "outdoor",
    duration: 90,
    icon: "🌳",
    description: "Popular garden with Ganesh temple and peaceful atmosphere",
    mood: "relaxed",
    mapImage: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "koregaon-park",
    name: "Koregaon Park",
    category: "social",
    duration: 120,
    icon: "🍸",
    description: "Trendy area with cafes, pubs, and vibrant nightlife",
    mood: "energetic",
    mapImage: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "lal-mahal",
    name: "Lal Mahal",
    category: "entertainment",
    duration: 60,
    icon: "🏮",
    description: "Historic red palace of Chhatrapati Shivaji Maharaj",
    mood: "adventurous",
    mapImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "pune-okayama-park",
    name: "Pune-Okayama Park",
    category: "wellness",
    duration: 90,
    icon: "🌸",
    description: "Japanese-style garden with cherry blossoms and zen atmosphere",
    mood: "relaxed",
    mapImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "dagdusheth-temple",
    name: "Dagdusheth Halwai Temple",
    category: "wellness",
    duration: 45,
    icon: "🙏",
    description: "Famous Ganpati temple with spiritual significance",
    mood: "relaxed",
    mapImage: "https://images.unsplash.com/photo-1582632228632-c57d0fef3877?w=400&h=200&fit=crop&auto=format&q=80"
  },
  {
    id: "phoenix-mall",
    name: "Phoenix Mall of the Millennium",
    category: "entertainment",
    duration: 180,
    icon: "🛍️",
    description: "Premier shopping destination with restaurants and entertainment",
    mood: "happy"
  },
  {
    id: "phoenix-marketcity",
    name: "Phoenix MarketCity",
    category: "entertainment",
    duration: 180,
    icon: "🏬",
    description: "Modern shopping mall with multiplex and food court",
    mood: "happy"
  },
  {
    id: "parvati-hill",
    name: "Parvati Hill",
    category: "outdoor",
    duration: 120,
    icon: "🏔️",
    description: "Historic hilltop temple with panoramic city views",
    mood: "adventurous"
  },
  {
    id: "osho-ashram",
    name: "Osho International Meditation Resort",
    category: "wellness",
    duration: 120,
    icon: "🧘",
    description: "World-renowned meditation and spiritual center",
    mood: "relaxed"
  },
  {
    id: "khadakwasla-dam",
    name: "Khadakwasla Dam",
    category: "outdoor",
    duration: 150,
    icon: "🌊",
    description: "Scenic dam with boating and picnic spots",
    mood: "relaxed"
  },
  {
    id: "rajiv-gandhi-zoo",
    name: "Rajiv Gandhi Zoological Park",
    category: "entertainment",
    duration: 180,
    icon: "🦁",
    description: "Wildlife park with diverse animal species and safari",
    mood: "adventurous"
  },
]

export const WEEKEND_THEMES: WeekendTheme[] = [
  {
    id: "lazy",
    name: "Lazy Weekend",
    description: "Relax and recharge with low-key activities",
    color: "bg-blue-100 text-blue-800",
    suggestedActivities: ["reading", "movie-night", "spa-day", "meditation", "cooking"],
    primaryColor: "#3b82f6",
    secondaryColor: "#dbeafe",
    accentColor: "#1d4ed8",
    icon: "🛋️",
    image: "https://images.unsplash.com/photo-1542385151-efd9000785a0?q=80&w=500&h=300&fit=crop&auto=format",
    mood: "Peaceful & Restful",
    vibe: "Cozy blankets, warm tea, and gentle moments of self-care",
  },
  {
    id: "adventurous",
    name: "Adventurous Weekend",
    description: "Explore new places and try exciting activities",
    color: "bg-orange-100 text-orange-800",
    suggestedActivities: ["hiking", "cycling", "museum", "food-market", "concert"],
    primaryColor: "#f97316",
    secondaryColor: "#fed7aa",
    accentColor: "#ea580c",
    icon: "🏔️",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=500&h=300&fit=crop&auto=format",
    mood: "Thrilling & Explorative",
    vibe: "Mountain peaks, hidden trails, and breathtaking discoveries",
  },
  {
    id: "family",
    name: "Family Weekend",
    description: "Quality time with loved ones",
    color: "bg-green-100 text-green-800",
    suggestedActivities: ["family-time", "picnic", "cooking", "art-crafts", "movie-night"],
    primaryColor: "#22c55e",
    secondaryColor: "#dcfce7",
    accentColor: "#16a34a",
    icon: "👨‍👩‍👧‍👦",
    image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?q=80&w=500&h=300&fit=crop&auto=format",
    mood: "Warm & Connecting",
    vibe: "Laughter, shared meals, and precious memories together",
  },
  {
    id: "productive",
    name: "Productive Weekend",
    description: "Get things done while having fun",
    color: "bg-purple-100 text-purple-800",
    suggestedActivities: ["gardening", "cooking", "art-crafts", "workout", "reading"],
    primaryColor: "#a855f7",
    secondaryColor: "#f3e8ff",
    accentColor: "#9333ea",
    icon: "⚡",
    image: "https://images.unsplash.com/photo-1493770348161-369560ae357d?q=80&w=500&h=300&fit=crop&auto=format",
    mood: "Focused & Accomplished",
    vibe: "Creative projects, organized spaces, and satisfying achievements",
  },
  {
    id: "social",
    name: "Social Weekend",
    description: "Connect with friends and meet new people",
    color: "bg-pink-100 text-pink-800",
    suggestedActivities: ["friends-hangout", "party", "brunch", "restaurant", "concert"],
    primaryColor: "#ec4899",
    secondaryColor: "#fce7f3",
    accentColor: "#db2777",
    icon: "🎉",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=500&h=300&fit=crop&auto=format",
    mood: "Vibrant & Joyful",
    vibe: "Dancing lights, shared laughter, and unforgettable celebrations",
  },
]
