import type { Activity, WeekendTheme } from "./types"

export const PREDEFINED_ACTIVITIES: Activity[] = [
  // Outdoor Activities
  {
    id: "hiking",
    name: "Hiking",
    category: "outdoor",
    duration: 180,
    icon: "🥾",
    description: "Explore nature trails and enjoy fresh air",
    mood: "adventurous",
  },
  {
    id: "cycling",
    name: "Cycling",
    category: "outdoor",
    duration: 120,
    icon: "🚴",
    description: "Bike ride through scenic routes",
    mood: "energetic",
  },
  {
    id: "picnic",
    name: "Picnic",
    category: "outdoor",
    duration: 150,
    icon: "🧺",
    description: "Outdoor meal in a beautiful setting",
    mood: "relaxed",
  },
  {
    id: "gardening",
    name: "Gardening",
    category: "outdoor",
    duration: 90,
    icon: "🌱",
    description: "Tend to plants and flowers",
    mood: "relaxed",
  },

  // Indoor Activities
  {
    id: "reading",
    name: "Reading",
    category: "indoor",
    duration: 120,
    icon: "📚",
    description: "Dive into a good book",
    mood: "relaxed",
  },
  {
    id: "cooking",
    name: "Cooking",
    category: "indoor",
    duration: 90,
    icon: "👨‍🍳",
    description: "Prepare a delicious meal",
    mood: "happy",
  },
  {
    id: "art-crafts",
    name: "Arts & Crafts",
    category: "indoor",
    duration: 120,
    icon: "🎨",
    description: "Creative projects and DIY",
    mood: "happy",
  },
  {
    id: "gaming",
    name: "Gaming",
    category: "indoor",
    duration: 180,
    icon: "🎮",
    description: "Video games or board games",
    mood: "energetic",
  },

  // Social Activities
  {
    id: "friends-hangout",
    name: "Friends Hangout",
    category: "social",
    duration: 240,
    icon: "👥",
    description: "Spend quality time with friends",
    mood: "happy",
  },
  {
    id: "family-time",
    name: "Family Time",
    category: "social",
    duration: 180,
    icon: "👨‍👩‍👧‍👦",
    description: "Quality time with family",
    mood: "happy",
  },
  {
    id: "party",
    name: "Party",
    category: "social",
    duration: 300,
    icon: "🎉",
    description: "Celebrate with friends",
    mood: "energetic",
  },

  // Wellness Activities
  {
    id: "yoga",
    name: "Yoga",
    category: "wellness",
    duration: 60,
    icon: "🧘",
    description: "Mindful movement and stretching",
    mood: "relaxed",
  },
  {
    id: "meditation",
    name: "Meditation",
    category: "wellness",
    duration: 30,
    icon: "🕯️",
    description: "Mindfulness and relaxation",
    mood: "relaxed",
  },
  {
    id: "spa-day",
    name: "Spa Day",
    category: "wellness",
    duration: 180,
    icon: "🛁",
    description: "Self-care and pampering",
    mood: "relaxed",
  },
  {
    id: "workout",
    name: "Workout",
    category: "wellness",
    duration: 60,
    icon: "💪",
    description: "Exercise and fitness",
    mood: "energetic",
  },

  // Food Activities
  {
    id: "brunch",
    name: "Brunch",
    category: "food",
    duration: 120,
    icon: "🥞",
    description: "Late morning meal with friends",
    mood: "happy",
  },
  {
    id: "restaurant",
    name: "Restaurant Visit",
    category: "food",
    duration: 90,
    icon: "🍽️",
    description: "Dine out at a nice restaurant",
    mood: "happy",
  },
  {
    id: "food-market",
    name: "Food Market",
    category: "food",
    duration: 120,
    icon: "🛒",
    description: "Explore local farmers market",
    mood: "adventurous",
  },

  // Entertainment Activities
  {
    id: "movie-night",
    name: "Movie Night",
    category: "entertainment",
    duration: 150,
    icon: "🎬",
    description: "Watch movies at home or cinema",
    mood: "relaxed",
  },
  {
    id: "concert",
    name: "Concert",
    category: "entertainment",
    duration: 180,
    icon: "🎵",
    description: "Live music performance",
    mood: "energetic",
  },
  {
    id: "museum",
    name: "Museum Visit",
    category: "entertainment",
    duration: 150,
    icon: "🏛️",
    description: "Explore art and culture",
    mood: "adventurous",
  },
  {
    id: "shopping",
    name: "Shopping",
    category: "entertainment",
    duration: 180,
    icon: "🛍️",
    description: "Browse stores and find treasures",
    mood: "happy",
  },
]

export const WEEKEND_THEMES: WeekendTheme[] = [
  {
    id: "lazy",
    name: "Lazy Weekend",
    description: "Relax and recharge with low-key activities",
    color: "bg-blue-100 text-blue-800",
    suggestedActivities: ["reading", "movie-night", "spa-day", "meditation", "cooking"],
    primaryColor: "#3b82f6",
    secondaryColor: "#dbeafe",
    accentColor: "#1d4ed8",
    icon: "🛋️",
  },
  {
    id: "adventurous",
    name: "Adventurous Weekend",
    description: "Explore new places and try exciting activities",
    color: "bg-orange-100 text-orange-800",
    suggestedActivities: ["hiking", "cycling", "museum", "food-market", "concert"],
    primaryColor: "#f97316",
    secondaryColor: "#fed7aa",
    accentColor: "#ea580c",
    icon: "🏔️",
  },
  {
    id: "family",
    name: "Family Weekend",
    description: "Quality time with loved ones",
    color: "bg-green-100 text-green-800",
    suggestedActivities: ["family-time", "picnic", "cooking", "art-crafts", "movie-night"],
    primaryColor: "#22c55e",
    secondaryColor: "#dcfce7",
    accentColor: "#16a34a",
    icon: "👨‍👩‍👧‍👦",
  },
  {
    id: "productive",
    name: "Productive Weekend",
    description: "Get things done while having fun",
    color: "bg-purple-100 text-purple-800",
    suggestedActivities: ["gardening", "cooking", "art-crafts", "workout", "reading"],
    primaryColor: "#a855f7",
    secondaryColor: "#f3e8ff",
    accentColor: "#9333ea",
    icon: "⚡",
  },
  {
    id: "social",
    name: "Social Weekend",
    description: "Connect with friends and meet new people",
    color: "bg-pink-100 text-pink-800",
    suggestedActivities: ["friends-hangout", "party", "brunch", "restaurant", "concert"],
    primaryColor: "#ec4899",
    secondaryColor: "#fce7f3",
    accentColor: "#db2777",
    icon: "🎉",
  },
]
